### ISSUE TITLE
Functions idea

### ISSUE THREAD

**Issue by larayavrs** [Mokita77/cuarta_unidad_programacion#2]
Para que quede mas bonito podrías especificar en los parametros el tipo de parametro y también que tipo de dato retornará.

```python
def limpiar_pantalla():
    import os as limpiar
    limpiar.system("cls")
 ```
  
  ```python
  from os import system
  
  def ClearScreen(command: str) -> str:
      return system(command) or None
  ```
  
  Buen repositorio, hay varias cosas interesantes! good job.

**Comment by Mokita77** [comment]
Miren quien apareció
Que te pasó desaparecido

**Comment by BarbaraCarvajal** [comment]
Háblame al mail pls Barb.carvajalsaez@gmail.com
